# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{accessorize}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeff Rafter"]
  s.date = %q{2010-02-10}
  s.description = %q{Sometimes you need to keep rigid logs of who created, updated and even accessed the data in your database. Accessorize simplifies the process.}
  s.email = %q{jeff@socialrange.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "generators/accessorize/accessorize_generator.rb",
     "generators/accessorize/templates/initializer.rb",
     "generators/accessorize/templates/migration.rb",
     "lib/accessorize.rb",
     "lib/accessorize/accessor.rb",
     "lib/accessorize/base.rb",
     "lib/accessorize/config.rb",
     "lib/accessorize/extension.rb",
     "rails/init.rb",
     "test/accessorize_test.rb"
  ]
  s.homepage = %q{http://github.com/jeffrafter/accessorize}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Log all data access for your ActiveRecord models}
  s.test_files = [
    "test/accessorize_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

